# Homework 0 - Deep Learning Winter 2024
TA: Jerry Abu Ayoub

Student 1: Rajaa Haj 322512690

Student 2: Aseel Shaheen 212393532

**Submission Date and time: 28/11/2024 23:59**

Submission is in pairs only, delayed submissions will result in a 5 point deduction each day for maximum of 3 days.

in this assignment, you will experiment with some basic pytorch functions to manipulate data to understand the fundementals. read the text boxes and write your code in the code cells below to answer the questions and run the cells, when you finish all tasks, save the notebook and submit it in the course website.

submission notebook should have all code cells already run with their respective outputs, submitting notebooks with unrunned cells will also result in point deductions.

## Data Manipulation

It is impossible to get anything done if we cannot manipulate data. Generally, there are two important things we need to do with data: (i) acquire it and (ii) process it once it is inside the computer. There is no point in acquiring data if we do not even know how to store it, so let's get our hands dirty first by playing with synthetic data. We will start by introducing the tensor,
PyTorch's primary tool for storing and transforming data. If you have worked with NumPy before, you will notice that tensors are, by design, similar to NumPy's multi-dimensional array. Tensors support asynchronous computation on CPU, GPU and provide support for automatic differentiation.

## Getting Started

In the cell below import torch and any other libraries you want to use.

In [2]:
# write your code here
import torch


Tensors represent (possibly multi-dimensional) arrays of numerical values.
The simplest object we can create is a vector.

To start, use `arange` to create a row vector with 12 consecutive integers.

In [3]:
# write your code here
x = torch.arange(12.0, requires_grad=True)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
       requires_grad=True)

Print the shape of the tensor

In [4]:
# We can get the tensor shape through the shape attribute.
# write your code here
tensor_shape = x.shape
tensor_shape



torch.Size([12])

use 'size' to print the shape of the tensor again

In [5]:
# .shape is an alias for .size(), and was added to more closely match numpy
# write your code here
tensor_shape = x.size()
tensor_shape



torch.Size([12])

We use the `reshape` function to change the shape of one (possibly multi-dimensional) array, to another that contains the same number of elements.
For example, we can transform the shape of our line vector `x` to (3, 4), which contains the same values but interprets them as a matrix containing 3 rows and 4 columns. Note that although the shape has changed, the elements in `x` have not.

reshape the vector into a 3x4 martix and print the result

In [6]:
# write your code here
x=x.reshape((3,4))
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], grad_fn=<ViewBackward0>)

Reshaping by manually specifying each of the dimensions can get annoying. Once we know one of the dimensions, why should we have to perform the division our selves to determine the other? For example, above, to get a matrix with 3 rows, we had to specify that it should have 4 columns (to account for the 12 elements). Fortunately, PyTorch can automatically work out one dimension given the other.
We can invoke this capability by placing `-1` for the dimension that we would like PyTorch to automatically infer.

In our case, instead of
`x.reshape((3, 4))`, use `-1` to reshape the tensor.

In [7]:
# write your code here
x=x.reshape((3,-1))
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], grad_fn=<ViewBackward0>)

create a 2x3 float tensor

In [8]:
# write your code here
x=torch.rand((2,3),dtype=torch.float)
x


tensor([[0.1829, 0.6027, 0.5887],
        [0.1051, 0.0925, 0.6589]])

torch.Tensor() is just an alias to torch.FloatTensor() which is the default type of tensor, when no dtype is specified during tensor construction.

From the torch for numpy users notes, it seems that torch.Tensor() is a drop-in replacement of numpy.empty()

So, in essence torch.FloatTensor() and torch.empty() does the same job.

The `empty` method just grabs some memory and hands us back a matrix without setting the values of any of its entries. This is very efficient but it means that the entries might take any arbitrary values, including very big ones! Typically, we'll want our matrices initialized either with ones, zeros, some known constant or numbers randomly sampled from a known distribution.

Perhaps most often, we want an array of all zeros.

Create a 2x3x4 multidimensional tensor with all entries as zeros.

In [9]:
# write your code here
x=torch.zeros((2,3,4))
x

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

Create a 2x3x4 tensor with all entries as ones

In [10]:
# write your code here
x=torch.ones((2,3,4))
x

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

We can also specify the value of each element in the desired NDArray by supplying a Python list containing the numerical values.

create a 2d tensor with the following lists as entries:
[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]


In [11]:
# write your code here

y = torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])
y

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In some cases, we will want to randomly sample the values of each element in the tensor according to some known probability distribution. This is especially common when we intend to use the tensor as a parameter in a neural network.

write a snippet that creates a tensor with a shape of (3,4). Each of its elements is randomly sampled in a normal distribution with zero mean and unit variance.

In [12]:
# write your code here
mean=0
std=1
x=torch.normal(mean=mean,std=std,size=(3,4))
x

tensor([[ 0.6225,  0.8271,  0.9828, -1.5815],
        [-0.1275,  0.0250, -0.5197,  1.0806],
        [ 1.1565, -0.3257, -0.4671,  0.3202]])

## Operations

Oftentimes, we want to apply functions to arrays. Some of the simplest and most useful functions are the element-wise functions. These operate by performing a single scalar operation on the corresponding elements of two arrays. We can create an element-wise function from any function that maps from the scalars to the scalars. In math notations we would denote such a function as $f: \mathbb{R} \rightarrow \mathbb{R}$. Given any two vectors $\mathbf{u}$ and $\mathbf{v}$ *of the same shape*, and the function f,
we can produce a vector $\mathbf{c} = F(\mathbf{u},\mathbf{v})$ by setting $c_i \gets f(u_i, v_i)$ for all $i$. Here, we produced the vector-valued $F: \mathbb{R}^d \rightarrow \mathbb{R}^d$ by *lifting* the scalar function to an element-wise vector operation. In PyTorch, the common standard arithmetic operators (+,-,/,\*,\*\*) have all been *lifted* to element-wise operations for identically-shaped tensors of arbitrary shape. We can call element-wise operations on any two tensors of the same shape, including matrices.

create a float tensor "x" that has: 1 2 4 8 and an another tensor "y" of all 2s

compute and print the element wise operations of addition, subtraction, multiplication, division and exponentiation e^(for both tensors)


In [13]:
# write your code here

x = torch.tensor([1,2,4,8],dtype=torch.float)
y =torch.tensor ([2,2,2,2],dtype=torch.float)

add_result=torch.add(x,y)
print("Additiion result:\n",add_result)

sub_result=torch.sub(x,y)
print("\n Subtraction result:\n",sub_result)

mul_result=torch.mul(x,y)
print("\n Multiplication result:\n",mul_result)

div_result=torch.div(x,y)
print("\n Division result:\n ",div_result)

print("\nExponentiation Results:\n ")
x_exp=torch.exp(x)
print("e^x result:\n ",x_exp)

y_exp=torch.exp(y)
print("e^y result:\n",y_exp)


Additiion result:
 tensor([ 3.,  4.,  6., 10.])

 Subtraction result:
 tensor([-1.,  0.,  2.,  6.])

 Multiplication result:
 tensor([ 2.,  4.,  8., 16.])

 Division result:
  tensor([0.5000, 1.0000, 2.0000, 4.0000])

Exponentiation Results:
 
e^x result:
  tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])
e^y result:
 tensor([7.3891, 7.3891, 7.3891, 7.3891])


In addition to computations by element, we can also perform matrix operations, like matrix multiplication using the `mm` or `matmul` function. Next, we will perform matrix multiplication of `x` and the transpose of `y`. We define `x` as a matrix of 3 rows and 4 columns, and `y` is transposed into a matrix of 4 rows and 3 columns. The two matrices are multiplied to obtain a matrix of 3 rows and 3 columns.

define x as a 3x4 matrix with consecutive numbers from 0 to 11 and let y be a 2d array with the following lists as entries:

[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]

print the type of the tensors and print the multiplication of x and y transpose

In [14]:
# write your code here
x=torch.arange(12,dtype=torch.float).reshape((3,4))
y=torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]],dtype=torch.float)
y_T=y.T

print("x-tensor type:",x.type())
print("y-tensor type:",y.type())

print("x-tensor shape:",x.shape)
print("y-tenos shape:",y.shape)
print("y transpose- tensor shape:",y_T.shape)

mul_res=torch.matmul(x,y_T)
print("Multiplication of x and y transpose result:\n",mul_res)
print("Mul result shape:",mul_res.shape)



x-tensor type: torch.FloatTensor
y-tensor type: torch.FloatTensor
x-tensor shape: torch.Size([3, 4])
y-tenos shape: torch.Size([3, 4])
y transpose- tensor shape: torch.Size([4, 3])
Multiplication of x and y transpose result:
 tensor([[ 18.,  20.,  10.],
        [ 58.,  60.,  50.],
        [ 98., 100.,  90.]])
Mul result shape: torch.Size([3, 3])


Note that torch.dot() behaves differently to np.dot(). There's been some discussion about what would be desirable here. Specifically, torch.dot() treats both x and y as 1D vectors (irrespective of their original shape) and computes their inner product.

We can also merge multiple tensors. For that, we need to tell the system along which dimension to merge.

merge the previous two matrices along the row axis and column axis respectively.

In [15]:
# write your code here
# merge along the row axis
rows=torch.cat((x,y),dim=0)
print("Merged matrices along the row axis:\n",rows)



Merged matrices along the row axis:
 tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])


In [16]:
# write your code here
# merge along the column axis
cols=torch.cat((x,y),dim=1)
print("Merged matrices along the column axis:\n", cols)


Merged matrices along the column axis:
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])


construct a binary tensors via logical element wise equation, that is the entry is 1 if and only if the 2 elements are equal in the same position, otherwise its zero.

use tensors x and y and compute the binary tensor.

In [17]:
# write your code here
binary_tensor=torch.zeros_like(x)
binary_tensor[x==y]=1
binary_tensor

tensor([[0., 1., 0., 1.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Summing all the elements in the tensor yields an tensor with only one element.

Sum all of x's elements

In [18]:
# write your code here
sum_x=torch.sum(x)
print("Sum all of x's elemnts:",sum_x)

Sum all of x's elemnts: tensor(66.)


## Broadcast Mechanism

In the above section, we saw how to perform operations on two tensors of the same shape. When their shapes differ, a broadcasting mechanism may be triggered analogous to NumPy: first, copy the elements appropriately so that the two tensors have the same shape, and then carry out operations by element.

In [19]:
a = torch.arange(3, dtype=torch.float).reshape((3, 1))
b = torch.arange(2, dtype=torch.float).reshape((1, 2))
a, b

(tensor([[0.],
         [1.],
         [2.]]),
 tensor([[0., 1.]]))

Since `a` and `b` are (3x1) and (1x2) matrices respectively, their shapes do not match up if we want to add them. PyTorch addresses this by 'broadcasting' the entries of both matrices into a larger (3x2) matrix as follows: for matrix `a` it replicates the columns, for matrix `b` it replicates the rows before adding up both element-wise.

add a and b and see for yourself

In [20]:
sum=torch.add(a,b)
sum

tensor([[0., 1.],
        [1., 2.],
        [2., 3.]])

## Indexing and Slicing

Just like in any other Python array, elements in a tensor can be accessed by its index. In good Python tradition the first element has index 0 and ranges are specified to include the first but not the last element.

use the ":' operand to select and print the first and second rows in x

In [21]:
# write your code here
first_r=x[0,:]
secound_r=x[1,:]

print("First row:\n",first_r)
print("Secound row:\n",secound_r)


First row:
 tensor([0., 1., 2., 3.])
Secound row:
 tensor([4., 5., 6., 7.])


Beyond reading, we can also write elements of a matrix like usual

write 9 in position 1,2 in x and print x

In [22]:
# write your code here
x[1,2]=9
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

use slicing to write 12 in the first and second rows of the matirx

In [23]:
# write your code here
x[0,:]=12
x[1,:]=12
x

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

## Saving Memory

In the previous example, every time we ran an operation, we allocated new memory to host its results. For example, if we write `y = x + y`, we will dereference the matrix that `y` used to point to and instead point it at the newly allocated memory. In the following example we demonstrate this with Python's `id()` function, which gives us the exact address of the referenced object in memory. After running `y = y + x`, we will find that `id(y)` points to a different location. That is because Python first evaluates `y + x`, allocating new memory for the result and then subsequently redirects `y` to point at this new location in memory.

use id() to check if the first y tensor is in the same memory of the resul y tensor

In [24]:
before = id(y)
y = y + x
id(y) == before

False

This might be undesirable for two reasons. First, we do not want to run around allocating memory unnecessarily all the time. In machine learning, we might have hundreds of megabytes of parameters and update all of them multiple times per second. Typically, we will want to perform these updates *in place*. Second, we might point at the same parameters from multiple variables. If we do not update in place, this could cause a memory leak, making it possible for us to inadvertently reference stale parameters.

Fortunately, performing in-place operations in PyTorch is easy. We can assign the result of an operation to a previously allocated array with slice notation, e.g., `y[:] = <expression>`. To illustrate the behavior, we first clone the shape of a matrix using `zeros_like` to allocate a block of 0 entries.

allocate a block of zeroes into a tensor named z, print the id of z, perfomr the addition of x and y into z and print the id of z again.

In [25]:
# write your code here
z=torch.zeros_like(x)
before=id(z)
print("z id- before:",before)
z[:]=torch.add(x,y)
print("z id - after:",id(z))




z id- before: 136347456947840
z id - after: 136347456947840


## Mutual Transformation of PyTorch and NumPy

Converting PyTorch Tensors to and from NumPy Arrays is easy. The converted arrays do *not* share memory. This minor inconvenience is actually quite important: when you perform operations on the CPU or one of the GPUs, you do not want PyTorch having to wait whether NumPy might want to be doing something else with the same chunk of memory. `.tensor` and `.numpy` do the trick.

convert "a" to a torch tensor and put in "b" then print b's type to ensure it's a tensor

In [26]:
# Write your code here
a = x.numpy()
print(type(a))
b=torch.tensor(a)
print(type(b))


<class 'numpy.ndarray'>
<class 'torch.Tensor'>


## Usage of Latex and Mathematics notations, usage of Autograd in pytorch

Use Latex to write down the 2 variable bell function (Recall from calculus 2), write it in understandable tidy mathematical formation (the most simple one).

\begin{align}
        \mathbf {g(x,y)={\frac{1}{2{\Pi}}}exp({-\frac{x^2 + y^2}{2}})}
      \end{align}

Use Latex again to write the gradient of the function, it should appear in a nice understandable mathematical format.

\begin{align}
        \mathbf {\nabla g(x,y)=(\frac{\partial g}{\partial x},\frac{\partial g}{\partial y})}
      \end{align}

 \begin{align}
        \mathbf {\frac{\partial g}{\partial x}= -\frac{x}{2\pi}exp({-\frac{x^2 + y^2}{2}})}
      \end{align}

 \begin{align}
        \mathbf {\frac{\partial g}{\partial y}= -\frac{y}{2\pi}exp({-\frac{x^2 + y^2}{2}})}
      \end{align}    

   \begin{align}
        \mathbf {\nabla g(x,y)=(-\frac{x}{2\pi}exp({-\frac{x^2 + y^2}{2}}),\frac{y}{2\pi}exp({-\frac{x^2 + y^2}{2}}))}
      \end{align}   

write a piece code in the cell below using pytorch to do the following:

- define the bell function
- print it's value at (0,0) and (1,1)
- print the gradient's value at those points

In [27]:
# write your code here

def bell_function(x,y):

    return (1/(2*torch.pi))*torch.exp(-0.5 *(x**2 + y**2))


def compute_grad(x,y):

   x_t=torch.tensor(float(x),requires_grad=True)
   y_t=torch.tensor(float(y),requires_grad=True)

   z=bell_function(x_t,y_t)

   # compute the gradient
   z.backward()

   x_grad=x_t.grad.item()
   y_grad=x_t.grad.item()
   z=z.item()

   #reset the gradient to zero
   x_t.grad.zero_()
   y_t.grad.zero_()

   return z,x_grad,y_grad

points=[(0,0),(1,1)]

for x,y in points :

  # get the value and gradient at p
  value,grad_x,grad_y=compute_grad(x,y)

  print(f"Point:{x,y}")
  print(f"the value of the bell function:{value}")
  print(f"the gradient of x:{grad_x}")
  print(f"the gradient of y:{grad_y}")


Point:(0, 0)
the value of the bell function:0.15915493667125702
the gradient of x:-0.0
the gradient of y:-0.0
Point:(1, 1)
the value of the bell function:0.058549828827381134
the gradient of x:-0.058549828827381134
the gradient of y:-0.058549828827381134
